CREATE DATABASE CADENA_HOTELERA;

USE CADENA_HOTELERA;

--- Crear tablas



CREATE TABLE TELEFONOS_CLIENTES(
	ID_Telefono INT IDENTITY (1,1) PRIMARY KEY,
	Numero_Telefono_Cliente INT NOT NULL,
	ID_Cliente INT NOT NULL,
	FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente)
	);

CREATE TABLE TELEFONOS_HOTELES(
	ID_Telefono INT IDENTITY (1,1) PRIMARY KEY,
	Numero_Telefono_Hotel INT NOT NULL,
	ID_Hotel INT NOT NULL,
	FOREIGN KEY (ID_Hotel) REFERENCES HOTELES(ID_Hotel)
	);

CREATE TABLE HABITACIONES(
	ID_Habitacion INT IDENTITY (1,1) PRIMARY KEY,
	Numero INT NOT NULL,
	Tipo VARCHAR(50) NOT NULL,
	Precio_Noche DECIMAL(10,2) NOT NULL,
	Estado VARCHAR(50) NOT NULL,
	ID_Hotel INT NOT NULL,
	FOREIGN KEY (ID_Hotel) references HOTELES(ID_Hotel)
	);

CREATE TABLE EMPLEADOS(
	ID_Empleado INT IDENTITY (1,1) PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Apellido1 VARCHAR(50) NOT NULL,
	Apellido2 VARCHAR(50) NOT NULL,
	Puesto VARCHAR(50) NOT NULL,
	Estado VARCHAR(50) NOT NULL,
	ID_Hotel INT NOT NULL,
	FOREIGN KEY (ID_Hotel) REFERENCES HOTELES(ID_Hotel)
	);

CREATE TABLE RESERVACIONES(
	ID_Reservacion INT IDENTITY (1,1) PRIMARY KEY,
	Fecha_Entrada DATE NOT NULL,
	Fecha_Salida DATE NOT NULL,
	Estado VARCHAR(50) NOT NULL,
	ID_Cliente INT NOT NULL,
	ID_Hotel INT NOT NULL,
	ID_Habitacion INT NOT NULL,
	FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente),
	FOREIGN KEY (ID_Hotel) REFERENCES HOTELES(ID_Hotel),
	FOREIGN KEY (ID_Habitacion) REFERENCES HABITACIONES(ID_Habitacion)
	);